recurs: main.o
	g++ -g main.o -std=c++0x -o recurs

main.o: main.cpp
	g++ -c main.cpp

inputValidation.o: inputValidation.cpp inputValidation.hpp
	g++ -c inputValidation.cpp

functions.o: functions.cpp functions.hpp
	g++ -c functions.cpp
