warGame: main.o
	g++ -g main.o -std=c++0x -o warGame
	
main.o: main.cpp
	g++ -c main.cpp
	
inputValidation.o: inputValidation.cpp inputValidation.hpp
	g++ -c inputValidation.cpp
	
game.o: game.cpp game.hpp
	g++ -c game.cpp
	
loadDie.o: loadDie.cpp loadDie.hpp
	g++ -c loadDie.cpp
	
die.o: die.cpp die.hpp
	g++ -c die.cpp
