survive: main.o
	g++ -g main.o -g -std=c++0x -o survive

main.o: main.cpp
	g++ -c -g -std=c++0x main.cpp

church.o: Church.h
	g++ -c Church.cpp

enums.o: Enums.h
	g++ -c Enums.cpp

game.o: Game.h
	g++ -c Game.cpp

inputValidation.o: inputValidation.h
	g++ -c inputValidation.h

ladder.o: Ladder.h
	g++ -c Ladder.cpp
	
menu.o: Menu.h
	g++ -c Menu.cpp
	
player.o: Player.h
	g++ -c Player.cpp
	
radio.o: Radio.h
	g++ -c Radio.cpp
	
school.o: School.h
	g++ -c School.cpp
	
shelter.o: Shelter.h
	g++ -c Shelter.cpp
	
space.o: Space.h
	g++ -c Space.cpp

clean:
	rm -f *o survive