OSUinfo: main.o
	g++ -g main.o -std=c++0x -o osuInfo

main.o: main.cpp
	g++ -std=c++0x -c main.cpp

university.o: university.cpp
	g++ -std=c++0x -c university.cpp

person.o: person.cpp
	g++ -std=c++0x -c person.cpp

building.o: building.cpp
	g++ -std=c++0x -c building.cpp

inputValidation.o: inputValidation.cpp inputValidation.hpp
	g++ -std=c++0x -c inputValidation.cpp